### ISSUE TITLE
Not able to connect the Avalara server in  application

### ISSUE THREAD

**Issue by Noushida** [avadev/AvaTaxClientLibrary#36]
Hi
I am not able to connect the Avalara server in my application(Visual studio 2015 and .net framework 4.7).I have installed Avalara.AvaTax -Version 17.5.0.67.  and   my code is
 var uri = new System.Uri("https://sandbox-rest.avatax.com");
                Client = new AvaTaxClient(typeof(vvv).Assembly.FullName,
                  typeof(vvv).Assembly.GetName().Version.ToString(),
                  Environment.MachineName,uri)
                  .WithSecurity("AccountID", "Liscence Key");
 TestCompany = Client.CompanyInitialize(new CompanyInitializationModel()
                {
                    city = "Bainbridge Island",
                    companyCode = Guid.NewGuid().ToString().Substring(0, 25),
                    country = "US",
                    email = "bob@example.org",
                    faxNumber = null,
                    firstName = "Bob",
                    lastName = "McExample",
                    line1 = "100 Ravine Lane",
                    mobileNumber = "206 555 1212",
                    phoneNumber = "206 555 1212",
                    postalCode = "98110",
                    region = "WA",
                    taxpayerIdNumber = "123456789",
                    name = "Bob's Greatest Popcorn",
                    title = "Owner/CEO"
                });
while running application,not able to connect this api server.

**Comment by ted-spence-avalara** [comment]
Hi Noushida!  This repository keeps track of our software development kits, and we don't monitor issues here very regularly.  Could you please post your comment on the Avalara Community Forums - https://community.avalara.com - where I can ask a team member to help you out?

We also have a good wiki page that explains common troubleshooting practices that might help: https://developer.avalara.com/avatax/authentication-in-rest
